[build]
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "npx prisma db push --accept-data-loss && npx ts-node --transpile-only src/app.ts"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
