[build]
buildCommand = "npm install && npx prisma generate"

[deploy]
startCommand = "npm run build && npx prisma migrate deploy && node dist/app.js"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
